# Generated by Django 5.0.9 on 2024-11-28 21:00

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('features', '0001_initial'),
        ('resource_files', '0001_initial'),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='linestring',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='resources.linestringvectorlayer'),
        ),
        migrations.AddField(
            model_name='linestring',
            name='source_file',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_files.resourcelinestringsfile'),
        ),
        migrations.AddField(
            model_name='multilinestring',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='resources.multilinestringvectorlayer'),
        ),
        migrations.AddField(
            model_name='multilinestring',
            name='source_file',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_files.resourcemultilinestringsfile'),
        ),
        migrations.AddField(
            model_name='multipoint',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='resources.multipointvectorlayer'),
        ),
        migrations.AddField(
            model_name='multipoint',
            name='source_file',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_files.resourcemultipointsfile'),
        ),
        migrations.AddField(
            model_name='multipolygon',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='resources.multipolygonvectorlayer'),
        ),
        migrations.AddField(
            model_name='multipolygon',
            name='source_file',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_files.resourcemultipolygonsfile'),
        ),
        migrations.AddField(
            model_name='point',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='resources.pointvectorlayer'),
        ),
        migrations.AddField(
            model_name='point',
            name='source_file',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_files.resourcepointsfile'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='layer',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='resources.polygonvectorlayer'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='source_file',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resource_files.resourcepolygonsfile'),
        ),
    ]
