from django.utils.translation import gettext_lazy as _

LINK_TYPES = ["original", "data", "image", "metadata", "html", "OGC:WMS", "OGC:WFS", "OGC:WCS"]

DEFAULT_SUPPLEMENTAL_INFORMATION = _(_("No information provided"))

COUNTRIES = (
    ("AFG", "Afghanistan"),
    ("ALA", "Aland Islands"),
    ("ALB", "Albania"),
    ("DZA", "Algeria"),
    ("ASM", "American Samoa"),
    ("AND", "Andorra"),
    ("AGO", "Angola"),
    ("AIA", "Anguilla"),
    ("ATG", "Antigua and Barbuda"),
    ("ARG", "Argentina"),
    ("ARM", "Armenia"),
    ("ABW", "Aruba"),
    ("AUS", "Australia"),
    ("AUT", "Austria"),
    ("AZE", "Azerbaijan"),
    ("BHS", "Bahamas"),
    ("BHR", "Bahrain"),
    ("BGD", "Bangladesh"),
    ("BRB", "Barbados"),
    ("BLR", "Belarus"),
    ("BEL", "Belgium"),
    ("BLZ", "Belize"),
    ("BEN", "Benin"),
    ("BMU", "Bermuda"),
    ("BTN", "Bhutan"),
    ("BOL", "Bolivia"),
    ("BIH", "Bosnia and Herzegovina"),
    ("BWA", "Botswana"),
    ("BRA", "Brazil"),
    ("VGB", "British Virgin Islands"),
    ("BRN", "Brunei Darussalam"),
    ("BGR", "Bulgaria"),
    ("BFA", "Burkina Faso"),
    ("BDI", "Burundi"),
    ("KHM", "Cambodia"),
    ("CMR", "Cameroon"),
    ("CAN", "Canada"),
    ("CPV", "Cape Verde"),
    ("CYM", "Cayman Islands"),
    ("CAF", "Central African Republic"),
    ("TCD", "Chad"),
    ("CIL", "Channel Islands"),
    ("CHL", "Chile"),
    ("CHN", "China"),
    ("HKG", "China - Hong Kong"),
    ("MAC", "China - Macao"),
    ("COL", "Colombia"),
    ("COM", "Comoros"),
    ("COG", "Congo"),
    ("COK", "Cook Islands"),
    ("CRI", "Costa Rica"),
    ("CIV", "Cote d'Ivoire"),
    ("HRV", "Croatia"),
    ("CUB", "Cuba"),
    ("CYP", "Cyprus"),
    ("CZE", "Czech Republic"),
    ("PRK", "Democratic People's Republic of Korea"),
    ("COD", "Democratic Republic of the Congo"),
    ("DNK", "Denmark"),
    ("DJI", "Djibouti"),
    ("DMA", "Dominica"),
    ("DOM", "Dominican Republic"),
    ("ECU", "Ecuador"),
    ("EGY", "Egypt"),
    ("SLV", "El Salvador"),
    ("GNQ", "Equatorial Guinea"),
    ("ERI", "Eritrea"),
    ("EST", "Estonia"),
    ("ETH", "Ethiopia"),
    ("FRO", "Faeroe Islands"),
    ("FLK", "Falkland Islands (Malvinas)"),
    ("FJI", "Fiji"),
    ("FIN", "Finland"),
    ("FRA", "France"),
    ("GUF", "French Guiana"),
    ("PYF", "French Polynesia"),
    ("GAB", "Gabon"),
    ("GMB", "Gambia"),
    ("GEO", "Georgia"),
    ("DEU", "Germany"),
    ("GHA", "Ghana"),
    ("GIB", "Gibraltar"),
    ("GRC", "Greece"),
    ("GRL", "Greenland"),
    ("GRD", "Grenada"),
    ("GLP", "Guadeloupe"),
    ("GUM", "Guam"),
    ("GTM", "Guatemala"),
    ("GGY", "Guernsey"),
    ("GIN", "Guinea"),
    ("GNB", "Guinea-Bissau"),
    ("GUY", "Guyana"),
    ("HTI", "Haiti"),
    ("VAT", "Holy See (Vatican City)"),
    ("HND", "Honduras"),
    ("HUN", "Hungary"),
    ("ISL", "Iceland"),
    ("IND", "India"),
    ("IDN", "Indonesia"),
    ("IRN", "Iran"),
    ("IRQ", "Iraq"),
    ("IRL", "Ireland"),
    ("IMN", "Isle of Man"),
    ("ISR", "Israel"),
    ("ITA", "Italy"),
    ("JAM", "Jamaica"),
    ("JPN", "Japan"),
    ("JEY", "Jersey"),
    ("JOR", "Jordan"),
    ("KAZ", "Kazakhstan"),
    ("KEN", "Kenya"),
    ("KIR", "Kiribati"),
    ("KWT", "Kuwait"),
    ("KGZ", "Kyrgyzstan"),
    ("LAO", "Lao People's Democratic Republic"),
    ("LVA", "Latvia"),
    ("LBN", "Lebanon"),
    ("LSO", "Lesotho"),
    ("LBR", "Liberia"),
    ("LBY", "Libyan Arab Jamahiriya"),
    ("LIE", "Liechtenstein"),
    ("LTU", "Lithuania"),
    ("LUX", "Luxembourg"),
    ("MKD", "Macedonia"),
    ("MDG", "Madagascar"),
    ("MWI", "Malawi"),
    ("MYS", "Malaysia"),
    ("MDV", "Maldives"),
    ("MLI", "Mali"),
    ("MLT", "Malta"),
    ("MHL", "Marshall Islands"),
    ("MTQ", "Martinique"),
    ("MRT", "Mauritania"),
    ("MUS", "Mauritius"),
    ("MYT", "Mayotte"),
    ("MEX", "Mexico"),
    ("FSM", "Micronesia, Federated States of"),
    ("MCO", "Monaco"),
    ("MNG", "Mongolia"),
    ("MNE", "Montenegro"),
    ("MSR", "Montserrat"),
    ("MAR", "Morocco"),
    ("MOZ", "Mozambique"),
    ("MMR", "Myanmar"),
    ("NAM", "Namibia"),
    ("NRU", "Nauru"),
    ("NPL", "Nepal"),
    ("NLD", "Netherlands"),
    ("ANT", "Netherlands Antilles"),
    ("NCL", "New Caledonia"),
    ("NZL", "New Zealand"),
    ("NIC", "Nicaragua"),
    ("NER", "Niger"),
    ("NGA", "Nigeria"),
    ("NIU", "Niue"),
    ("NFK", "Norfolk Island"),
    ("MNP", "Northern Mariana Islands"),
    ("NOR", "Norway"),
    ("PSE", "Occupied Palestinian Territory"),
    ("OMN", "Oman"),
    ("PAK", "Pakistan"),
    ("PLW", "Palau"),
    ("PAN", "Panama"),
    ("PNG", "Papua New Guinea"),
    ("PRY", "Paraguay"),
    ("PER", "Peru"),
    ("PHL", "Philippines"),
    ("PCN", "Pitcairn"),
    ("POL", "Poland"),
    ("PRT", "Portugal"),
    ("PRI", "Puerto Rico"),
    ("QAT", "Qatar"),
    ("KOR", "Republic of Korea"),
    ("MDA", "Republic of Moldova"),
    ("REU", "Reunion"),
    ("ROU", "Romania"),
    ("RUS", "Russian Federation"),
    ("RWA", "Rwanda"),
    ("BLM", "Saint-Barthelemy"),
    ("SHN", "Saint Helena"),
    ("KNA", "Saint Kitts and Nevis"),
    ("LCA", "Saint Lucia"),
    ("MAF", "Saint-Martin (French part)"),
    ("SPM", "Saint Pierre and Miquelon"),
    ("VCT", "Saint Vincent and the Grenadines"),
    ("WSM", "Samoa"),
    ("SMR", "San Marino"),
    ("STP", "Sao Tome and Principe"),
    ("SAU", "Saudi Arabia"),
    ("SEN", "Senegal"),
    ("SRB", "Serbia"),
    ("SYC", "Seychelles"),
    ("SLE", "Sierra Leone"),
    ("SGP", "Singapore"),
    ("SVK", "Slovakia"),
    ("SVN", "Slovenia"),
    ("SLB", "Solomon Islands"),
    ("SOM", "Somalia"),
    ("ZAF", "South Africa"),
    ("SSD", "South Sudan"),
    ("ESP", "Spain"),
    ("LKA", "Sri Lanka"),
    ("SDN", "Sudan"),
    ("SUR", "Suriname"),
    ("SJM", "Svalbard and Jan Mayen Islands"),
    ("SWZ", "Swaziland"),
    ("SWE", "Sweden"),
    ("CHE", "Switzerland"),
    ("SYR", "Syrian Arab Republic"),
    ("TJK", "Tajikistan"),
    ("THA", "Thailand"),
    ("TLS", "Timor-Leste"),
    ("TGO", "Togo"),
    ("TKL", "Tokelau"),
    ("TON", "Tonga"),
    ("TTO", "Trinidad and Tobago"),
    ("TUN", "Tunisia"),
    ("TUR", "Turkey"),
    ("TKM", "Turkmenistan"),
    ("TCA", "Turks and Caicos Islands"),
    ("TUV", "Tuvalu"),
    ("UGA", "Uganda"),
    ("UKR", "Ukraine"),
    ("ARE", "United Arab Emirates"),
    ("GBR", "United Kingdom"),
    ("TZA", "United Republic of Tanzania"),
    ("USA", "United States of America"),
    ("VIR", "United States Virgin Islands"),
    ("URY", "Uruguay"),
    ("UZB", "Uzbekistan"),
    ("VUT", "Vanuatu"),
    ("VEN", "Venezuela (Bolivarian Republic of)"),
    ("VNM", "Viet Nam"),
    ("WLF", "Wallis and Futuna Islands"),
    ("ESH", "Western Sahara"),
    ("YEM", "Yemen"),
    ("ZMB", "Zambia"),
    ("ZWE", "Zimbabwe"),
)

# Taken from http://www.w3.org/WAI/ER/IG/ert/iso639.htm
ALL_LANGUAGES = (
    ("abk", "Abkhazian"),
    ("aar", "Afar"),
    ("afr", "Afrikaans"),
    ("amh", "Amharic"),
    ("ara", "Arabic"),
    ("asm", "Assamese"),
    ("aym", "Aymara"),
    ("aze", "Azerbaijani"),
    ("bak", "Bashkir"),
    ("ben", "Bengali"),
    ("bih", "Bihari"),
    ("bis", "Bislama"),
    ("bre", "Breton"),
    ("bul", "Bulgarian"),
    ("bel", "Byelorussian"),
    ("cat", "Catalan"),
    ("chi", "Chinese"),
    ("cos", "Corsican"),
    ("dan", "Danish"),
    ("dzo", "Dzongkha"),
    ("eng", "English"),
    ("fra", "French"),
    ("epo", "Esperanto"),
    ("est", "Estonian"),
    ("fao", "Faroese"),
    ("fij", "Fijian"),
    ("fin", "Finnish"),
    ("fry", "Frisian"),
    ("glg", "Gallegan"),
    ("ger", "German"),
    ("gre", "Greek"),
    ("kal", "Greenlandic"),
    ("grn", "Guarani"),
    ("guj", "Gujarati"),
    ("hau", "Hausa"),
    ("heb", "Hebrew"),
    ("hin", "Hindi"),
    ("hun", "Hungarian"),
    ("ind", "Indonesian"),
    ("ina", "Interlingua (International Auxiliary language Association)"),
    ("iku", "Inuktitut"),
    ("ipk", "Inupiak"),
    ("ita", "Italian"),
    ("jpn", "Japanese"),
    ("kan", "Kannada"),
    ("kas", "Kashmiri"),
    ("kaz", "Kazakh"),
    ("khm", "Khmer"),
    ("kin", "Kinyarwanda"),
    ("kir", "Kirghiz"),
    ("kor", "Korean"),
    ("kur", "Kurdish"),
    ("oci", "Langue d 'Oc (post 1500)"),
    ("lao", "Lao"),
    ("lat", "Latin"),
    ("lav", "Latvian"),
    ("lin", "Lingala"),
    ("lit", "Lithuanian"),
    ("mlg", "Malagasy"),
    ("mlt", "Maltese"),
    ("mar", "Marathi"),
    ("mol", "Moldavian"),
    ("mon", "Mongolian"),
    ("nau", "Nauru"),
    ("nep", "Nepali"),
    ("nor", "Norwegian"),
    ("ori", "Oriya"),
    ("orm", "Oromo"),
    ("pan", "Panjabi"),
    ("pol", "Polish"),
    ("por", "Portuguese"),
    ("pus", "Pushto"),
    ("que", "Quechua"),
    ("roh", "Rhaeto-Romance"),
    ("run", "Rundi"),
    ("rus", "Russian"),
    ("smo", "Samoan"),
    ("sag", "Sango"),
    ("san", "Sanskrit"),
    ("scr", "Serbo-Croatian"),
    ("sna", "Shona"),
    ("snd", "Sindhi"),
    ("sin", "Singhalese"),
    ("ssw", "Siswant"),
    ("slv", "Slovenian"),
    ("som", "Somali"),
    ("sot", "Sotho"),
    ("spa", "Spanish"),
    ("sun", "Sudanese"),
    ("swa", "Swahili"),
    ("tgl", "Tagalog"),
    ("tgk", "Tajik"),
    ("tam", "Tamil"),
    ("tat", "Tatar"),
    ("tel", "Telugu"),
    ("tha", "Thai"),
    ("tir", "Tigrinya"),
    ("tog", "Tonga (Nyasa)"),
    ("tso", "Tsonga"),
    ("tsn", "Tswana"),
    ("tur", "Turkish"),
    ("tuk", "Turkmen"),
    ("twi", "Twi"),
    ("uig", "Uighur"),
    ("ukr", "Ukrainian"),
    ("urd", "Urdu"),
    ("uzb", "Uzbek"),
    ("vie", "Vietnamese"),
    ("vol", "Volapük"),
    ("wol", "Wolof"),
    ("xho", "Xhosa"),
    ("yid", "Yiddish"),
    ("yor", "Yoruba"),
    ("zha", "Zhuang"),
    ("zul", "Zulu"),
)

RESOURCE_TYPES = [
    ('', 'Resource type'),
    ('base', 'base'),
    ('vector_layer', 'vector_layer'),
    ('points_vector_layer', 'points_vector_layer'),
    ('linestrings_vector_layer', 'linestrings_vector_layer'),
    ('polygons_vector_layer', 'polygons_vector_layer'),
    ('multipoints_vector_layer', 'multipoints_vector_layer'),
    ('multilinestrings_vector_layer', 'multilinestrings_vector_layer'),
    ('multipolygons_vector_layer', 'multipolygons_vector_layer'),
    ('geometrycollections_vector_layer', 'geometrycollections_vector_layer'),
    ('raster_layer', 'raster_layer'),
    ('data_table', 'data_table'),
    ('image', 'image'),
    ('document', 'document'),
    ('map', 'map'),
    ('dashboard', 'dashboard'),
    ('story', 'story'),
    ('page', 'page'),
]

REMOTE_SERVICE_TYPES = [
    ('', 'Remote service type'),
    ('remote_wms', 'Remote WMS'),
    ('remote_wfs', 'Remote WFS'),
    ('remote_wcs', 'Remote WCS'),
    ('remote_csw', 'Remote CSW'),
    ('remote_generic_rest', 'Remote Generic RESTful API'),
    ('remote_arcgis_rest', 'Remote ArcGIS REST API'),
]

PROCESSING_STATES = (
    ('', 'Processing state'),
    ('running', 'Running'),
    ('waiting', 'Waiting'),
    ('complete', 'Complete'),
    ('ready', 'Ready'),
    ('invalid', 'Invalid'),
    ('error', 'Error')
)

SOURCE_TYPE_LOCAL = "LOCAL"
SOURCE_TYPE_REMOTE = "REMOTE"
SOURCE_TYPE_COPYREMOTE = "COPYREMOTE"

LAYER_TYPES = ["vector", "raster", "remote", "vector_time"]
