# Generated by Django 5.0.9 on 2024-11-28 21:00

import django.db.models.deletion
import resource_files.utils
import wagtail.models.media
import wagtail.search.index
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceMultiLineStringsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_multilinestring_vector_file])),
            ],
            options={
                'verbose_name': 'MultiLineString Vector Layer File',
                'verbose_name_plural': 'MultiLineString Vector Layer Files',
                'permissions': [('choose_document', 'Can choose document')],
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceMultiPointsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_multipoint_vector_file])),
            ],
            options={
                'verbose_name': 'MultiPoint Vector Layer File',
                'verbose_name_plural': 'MultiPoint Vector Layer Files',
                'permissions': [('choose_document', 'Can choose document')],
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceMultiPolygonsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_multipolygon_vector_file])),
            ],
            options={
                'verbose_name': 'MultiPolygon Vector Layer File',
                'verbose_name_plural': 'MultiPolygon Vector Layer Files',
                'permissions': [('choose_document', 'Can choose document')],
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ResourcePointsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_point_vector_file])),
            ],
            options={
                'verbose_name': 'Point Vector Layer File',
                'verbose_name_plural': 'Point Vector Layer Files',
                'permissions': [('choose_document', 'Can choose document')],
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ResourcePolygonsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_polygon_vector_file])),
            ],
            options={
                'verbose_name': 'Polygon Vector Layer File',
                'verbose_name_plural': 'Polygon Vector Layer Files',
                'permissions': [('choose_document', 'Can choose document')],
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
        migrations.CreateModel(
            name='ResourceLineStringsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('file_size', models.PositiveBigIntegerField(editable=False, null=True)),
                ('file_hash', models.CharField(blank=True, editable=False, max_length=40)),
                ('file', models.FileField(upload_to=resource_files.utils.uuid_file_path, validators=[resource_files.utils.validate_linestring_vector_file])),
                ('collection', models.ForeignKey(default=wagtail.models.media.get_root_collection_id, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.collection', verbose_name='collection')),
            ],
            options={
                'verbose_name': 'LineString Vector Layer File',
                'verbose_name_plural': 'LineString Vector Layer Files',
                'permissions': [('choose_document', 'Can choose document')],
                'abstract': False,
            },
            bases=(wagtail.search.index.Indexed, models.Model),
        ),
    ]
